### PR TITLE
cci integration, and make it pass

### PR DESCRIPTION
**Pull request by gquintard**
it would be nice for people forking this repository (even though vcdk exists) had a template for ci. The first commit add commit-triggered and weekly commits. And the second updates the code to make said tests pass.

### CODE REVIEW

**Comment by gquintard** [comment]
@Dridi , just checked: no need to change the yaml file when you rename the vmod

**Comment by dridi** [comment]
cough README cough

**Comment by gquintard** [comment]
already works as-is :-)

**Comment by dridi** [comment]
Nope, I followed the instructions and my README contains this:

```
$ ./rename-vmod-script foo
rm 'rename-vmod-script'
All done.

For your cut&paste needs:
git commit -a -m "Automatic rename of libvmod-example to libvmod-foo."
$ git commit -a -m "Automatic rename of libvmod-example to libvmod-foo."
[...git output...]
$ git grep CircleCI -- README.rst
README.rst:[![CircleCI](https://circleci.com/gh/varnishcache/libvmod-foo/tree/master.svg?style=svg)](https://app.circleci.com/pipelines/github/varnishcache/libvmod-foo?branch=master)
```

Make the rename script remove the line containing `CircleCI` from the README?

**Comment by gquintard** [comment]
oh, absolutely correct, the renaming is done, but make no sense since it's a URL. i added a commit to nuke the line

**Review by dridi — APPROVED** [review]

**Comment by gquintard** [comment]
rebased and pushed

**Pull request closed without merging**
